apiVersion: v1
kind: Service
metadata:
  name: server
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  selector:
    app: server
  ports:
    - name: http
      protocol: TCP
      port: 32257
      targetPort: 32257
  type: LoadBalancer
  loadBalancerIP: 146.148.49.10
