# Konflux uses Syft to generate container SBOMs.
# Syft config docs https://github.com/anchore/syft/wiki/configuration

# Here we exclude sample rpmdb files that come from StackRox from being parsed and merged into SBOM.
exclude:
- ./collector/proto/third_party/stackrox/**/rpmdb.sqlite
