extern crate cbindgen;

use std::env;
use std::path::Path;

fn main(){
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let target_dir = env::var("BINDINGS_INCLUDE_DIRECTORY").unwrap_or("./include".to_string());

    let path = Path::new(&target_dir).join("RustTest.h");

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_header("// clang-format off\n// This file is autogenerated DO NOT EDIT")
        .with_trailer("// clang-format on")
        .with_pragma_once(true)
        .with_namespace("collector::rust")
        .generate()
        .expect("Unable to generate bindings for Test library")
        .write_to_file(path);
}
