---
- name: Retag image to arch specific
  community.docker.docker_image:
    name: "{{ original_image }}"
    repository: "{{ target_image }}"
    source: local

- name: Untag collector builder image to prevent issues with multiarch
  community.docker.docker_image:
    name: "{{ original_image }}"
    state: absent
  when: untag_original

- name: Login to quay.io
  community.docker.docker_login:
    registry_url: quay.io
    username: "{{ username }}"
    password: "{{ password }}"

- name: Push builder image to quay.io/stackrox-io
  community.docker.docker_image:
    name: "{{ target_image }}"
    push: true
    source: local

- name: Logout of quay.io
  community.docker.docker_login:
    registry_url: quay.io
    state: absent
  when: true
