#!/bin/sh

if ! make -C collector check-staged; then
	echo "Format errors found! Run 'make -C collector format' in order to fix them."
	echo "Use the '--no-verify' flag in order to bypass the pre-commit check altogether."
	exit 1
fi
