---

- name: Provision VM
  hosts: "job_id_{{ lookup('env', 'JOB_ID') | default(0) }}"
  become: true

  tasks:
    - name: Platform specific provisioning
      include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"

    - name: Start docker service
      service:
        name: "docker"
        enabled: true
        state: started

    - name: Add user to docker group
      shell: "usermod -aG docker {{ ansible_user }}"

