---

- name: Provision VM
  hosts: "job_id_{{ lookup('env', 'JOB_ID', default='1') }}"
  strategy: free
  become: true

  tasks:
    - debug: msg="{{ ansible_facts['os_family'] }}"

    - name: RedHat Provisioning
      include_tasks: "redhat.yml"
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Ubuntu Provisioning
      include_tasks: "ubuntu.yml"
      when: ansible_facts['os_family'] == 'Ubuntu'

    - name: Start docker service
      service:
        name: "docker"
        enabled: true
        state: started

    - name: Add user to docker group
      shell: "usermod -aG docker {{ ansible_user }}"

