FROM debian:buster

RUN apt-get update \
 && apt-get upgrade -y \
 && apt-get install --no-install-recommends -y \
	curl;


COPY schedule-curls.sh /usr/bin/schedule-curls.sh 

RUN ls -l /usr/bin/schedule-curls.sh 
