#!/bin/bash
MACHINE_NAME=$1
if [[ -z $MACHINE_NAME ]] ; then
  echo Must supply machine name.
  exit 1
fi

gcloud compute instances create --image-family cos-stable --image-project cos-cloud --zone us-central1-a  "$MACHINE_NAME"
