// clang-format off
// This file is autogenerated DO NOT EDIT

#pragma once

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace collector::rust {

extern "C" {

uint64_t external_add(uint64_t left, uint64_t right);

} // extern "C"

} // namespace collector::rust

// clang-format on
