
runCircleGCPUbuntuTestViaSSH() {
  CIRCLE_BUILD_VM_NAME="collector-nb-${CIRCLE_BUILD_NUM}"

  createGCPVMUbuntu "$CIRCLE_BUILD_VM_NAME" "$GSOURCE_ROOT"
  installVariousAptDepsViaGCPSSH "$CIRCLE_BUILD_VM_NAME"
  loginDockerViaGCPSSH "$CIRCLE_BUILD_VM_NAME" "$GDOCKER_USER" "$GDOCKER_PASS"
  extractSourceTarballViaGCPSSH "$CIRCLE_BUILD_VM_NAME"
}

