FROM ubuntu:focal

RUN apt-get update -y && apt-get install -y xz-utils bpftrace && bpftrace -V

COPY /scripts /scripts
COPY /tools /tools

WORKDIR /root
ENTRYPOINT ["/scripts/run-tool.sh", "bpftrace"]
