FROM alpine:3.12

RUN apk add --update \
    bash \
    bc \
    build-base \
    bison \
    flex \
    curl \
    elfutils-dev \
    linux-headers \
    make \
    openssl-dev \
    diffutils

COPY tools /tools
COPY scripts /scripts