FROM alpine:latest

RUN apk add --update \
    bash \
    bc \
    build-base \
    bison \
    flex \
    curl \
    elfutils-dev \
    linux-headers \
    make \
    openssl-dev \
    diffutils

WORKDIR /

COPY /scripts/init.sh /
RUN chmod +x /init.sh
ENTRYPOINT [ "/init.sh" ]