/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/ghutton/code/go/src/github.com/FStarLang/FStar/karamel/krml -skip-linking -backend c -warn-error -2-15 -minimal -tmpdir extracted -bundle NetworkTypes -bundle NRadixPulse=NRadixPulse,NRadixSpec,FStar.Pervasives.Native out_NRadixPulse.krml
  F* version: <unknown>
  KaRaMeL version: 772e4f63642524f6fb3c15fcb1b9398dd6afea7f
 */

#include "internal/NetworkTypes.h"

NetworkTypes_address
NetworkTypes_null_address = { .hi = 0ULL, .lo = 0ULL, .family = NetworkTypes_FamilyUnknown };

NetworkTypes_ipnet NetworkTypes_mk_ipnet(NetworkTypes_address addr, uint8_t prefix)
{
  uint64_t mask_hi;
  if (prefix >= 64U)
    mask_hi = addr.hi;
  else if (prefix == 0U)
    mask_hi = 0ULL;
  else
  {
    uint8_t shift = 64U - (uint32_t)prefix;
    mask_hi = addr.hi & 0xffffffffffffffffULL >> (uint32_t)shift;
  }
  uint64_t mask_lo;
  if (prefix >= 128U)
    mask_lo = addr.lo;
  else if (prefix <= 64U)
    mask_lo = 0ULL;
  else
  {
    uint8_t lo_bits = (uint32_t)prefix - 64U;
    uint8_t shift = 64U - (uint32_t)lo_bits;
    mask_lo = addr.lo & 0xffffffffffffffffULL >> (uint32_t)shift;
  }
  return
    (
      (NetworkTypes_ipnet){ .addr = addr, .mask_hi = mask_hi, .mask_lo = mask_lo, .prefix = prefix }
    );
}

