/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/ghutton/code/go/src/github.com/FStarLang/FStar/karamel/krml -skip-linking -backend c -warn-error -2-15 -minimal -tmpdir extracted -bundle NetworkTypes -bundle NetworkOps=NetworkOps out_NetworkOps.krml
  F* version: <unknown>
  KaRaMeL version: 772e4f63642524f6fb3c15fcb1b9398dd6afea7f
 */

#ifndef NetworkOps_H
#define NetworkOps_H

#include "NetworkTypes.h"

bool NetworkOps_address_is_local(NetworkTypes_address a);

bool NetworkOps_is_private_ipv4(NetworkTypes_address a);

bool NetworkOps_is_private_ipv6(NetworkTypes_address a);

bool NetworkOps_address_is_public(NetworkTypes_address a);

uint8_t NetworkOps_is_ephemeral_port(uint16_t port);

bool NetworkOps_is_canonical_external(NetworkTypes_address a);


#define NetworkOps_H_DEFINED
#endif /* NetworkOps_H */
