/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/ghutton/code/go/src/github.com/FStarLang/FStar/karamel/krml -skip-linking -backend c -warn-error -2-15 -minimal -tmpdir extracted -bundle NetworkTypes -bundle NetworkOps=NetworkOps out_NetworkOps.krml
  F* version: <unknown>
  KaRaMeL version: 772e4f63642524f6fb3c15fcb1b9398dd6afea7f
 */

#include "NetworkOps.h"

#include "NetworkTypes.h"

bool NetworkOps_address_is_local(NetworkTypes_address a)
{
  switch (a.family)
  {
    case NetworkTypes_FamilyIPv4:
      {
        return (a.hi & 0x00000000000000ffULL) == 0x000000000000007fULL;
      }
    case NetworkTypes_FamilyIPv6:
      {
        if (!(a.hi == 0ULL))
          return false;
        else
          return
            a.lo == 0x0100000000000000ULL || (a.lo & 0x0000007fffff0000ULL) == 0x0000007fffff0000ULL;
        break;
      }
    case NetworkTypes_FamilyUnknown:
      {
        return false;
      }
    default:
      {
        KRML_HOST_EPRINTF("KaRaMeL incomplete match at %s:%d\n", __FILE__, __LINE__);
        KRML_HOST_EXIT(253U);
      }
  }
}

bool NetworkOps_is_private_ipv4(NetworkTypes_address a)
{
  return
    (a.hi & 0x00000000000000ffULL) == 0x000000000000000aULL ||
      (a.hi & 0x000000000000c0ffULL) == 0x0000000000004064ULL
    || (a.hi & 0x000000000000ffffULL) == 0x000000000000fea9ULL
    || (a.hi & 0x000000000000f0ffULL) == 0x00000000000010acULL
    || (a.hi & 0x000000000000ffffULL) == 0x000000000000a8c0ULL;
}

bool NetworkOps_is_private_ipv6(NetworkTypes_address a)
{
  return
    (a.hi & 0x00000000000000ffULL) == 0x00000000000000fdULL ||
      a.hi == 0ULL &&
        ((a.lo & 0x000000ffffff0000ULL) == 0x0000000affff0000ULL ||
          (a.lo & 0x0000c0ffffff0000ULL) == 0x00004064ffff0000ULL
        || (a.lo & 0x0000ffffffff0000ULL) == 0x0000fea9ffff0000ULL
        || (a.lo & 0x0000f0ffffff0000ULL) == 0x000010acffff0000ULL
        || (a.lo & 0x0000ffffffff0000ULL) == 0x0000a8c0ffff0000ULL);
}

bool NetworkOps_address_is_public(NetworkTypes_address a)
{
  switch (a.family)
  {
    case NetworkTypes_FamilyIPv4:
      {
        return
          !((a.hi & 0x00000000000000ffULL) == 0x000000000000000aULL ||
            (a.hi & 0x000000000000c0ffULL) == 0x0000000000004064ULL
          || (a.hi & 0x000000000000ffffULL) == 0x000000000000fea9ULL
          || (a.hi & 0x000000000000f0ffULL) == 0x00000000000010acULL
          || (a.hi & 0x000000000000ffffULL) == 0x000000000000a8c0ULL);
      }
    case NetworkTypes_FamilyIPv6:
      {
        return
          !((a.hi & 0x00000000000000ffULL) == 0x00000000000000fdULL ||
            a.hi == 0ULL &&
              ((a.lo & 0x000000ffffff0000ULL) == 0x0000000affff0000ULL ||
                (a.lo & 0x0000c0ffffff0000ULL) == 0x00004064ffff0000ULL
              || (a.lo & 0x0000ffffffff0000ULL) == 0x0000fea9ffff0000ULL
              || (a.lo & 0x0000f0ffffff0000ULL) == 0x000010acffff0000ULL
              || (a.lo & 0x0000ffffffff0000ULL) == 0x0000a8c0ffff0000ULL));
      }
    case NetworkTypes_FamilyUnknown:
      {
        return false;
      }
    default:
      {
        KRML_HOST_EPRINTF("KaRaMeL incomplete match at %s:%d\n", __FILE__, __LINE__);
        KRML_HOST_EXIT(253U);
      }
  }
}

uint8_t NetworkOps_is_ephemeral_port(uint16_t port)
{
  if (port >= 49152U)
    return 4U;
  else if (port >= 32768U)
    return 3U;
  else if (port >= 1025U && port <= 5000U)
    return 2U;
  else if (port == 1024U)
    return 1U;
  else
    return 0U;
}

bool NetworkOps_is_canonical_external(NetworkTypes_address a)
{
  switch (a.family)
  {
    case NetworkTypes_FamilyIPv4:
      {
        return (a.hi & 0x00000000ffffffffULL) == 0x00000000ffffffffULL;
      }
    case NetworkTypes_FamilyIPv6:
      {
        return a.hi == 0xffffffffffffffffULL && a.lo == 0xffffffffffffffffULL;
      }
    case NetworkTypes_FamilyUnknown:
      {
        return false;
      }
    default:
      {
        KRML_HOST_EPRINTF("KaRaMeL incomplete match at %s:%d\n", __FILE__, __LINE__);
        KRML_HOST_EXIT(253U);
      }
  }
}

