/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/ghutton/code/go/src/github.com/FStarLang/FStar/karamel/krml -skip-linking -backend c -warn-error -2-15 -minimal -tmpdir extracted -bundle NetworkTypes -bundle NetworkOps=NetworkOps out_NetworkOps.krml
  F* version: <unknown>
  KaRaMeL version: 772e4f63642524f6fb3c15fcb1b9398dd6afea7f
 */

#ifndef NetworkTypes_H
#define NetworkTypes_H

#define NetworkTypes_FamilyUnknown 0
#define NetworkTypes_FamilyIPv4 1
#define NetworkTypes_FamilyIPv6 2

typedef uint8_t NetworkTypes_address_family;

typedef struct NetworkTypes_address_s
{
  uint64_t hi;
  uint64_t lo;
  NetworkTypes_address_family family;
}
NetworkTypes_address;


#define NetworkTypes_H_DEFINED
#endif /* NetworkTypes_H */
