/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/ghutton/code/go/src/github.com/FStarLang/FStar/karamel/krml -skip-linking -backend c -warn-error -2-15 -minimal -tmpdir extracted -bundle NetworkTypes -bundle NRadixPulse=NRadixPulse,NRadixSpec,FStar.Pervasives.Native out_NRadixPulse.krml
  F* version: <unknown>
  KaRaMeL version: 772e4f63642524f6fb3c15fcb1b9398dd6afea7f
 */

#include "NRadixPulse.h"

#include "NetworkTypes.h"
#include "internal/NetworkTypes.h"

static uint64_t bswap64(uint64_t x)
{
  uint64_t b0 = x & 0xffULL;
  uint64_t b1 = x >> 8U & 0xffULL;
  uint64_t b2 = x >> 16U & 0xffULL;
  uint64_t b3 = x >> 24U & 0xffULL;
  uint64_t b4 = x >> 32U & 0xffULL;
  uint64_t b5 = x >> 40U & 0xffULL;
  uint64_t b6 = x >> 48U & 0xffULL;
  uint64_t b7 = x >> 56U & 0xffULL;
  return b0 << 56U | b1 << 48U | b2 << 40U | b3 << 32U | b4 << 24U | b5 << 16U | b6 << 8U | b7;
}

static uint64_t net_mask_hi(uint8_t prefix)
{
  if (prefix == 0U)
    return 0ULL;
  else if (prefix >= 64U)
    return 0xffffffffffffffffULL;
  else
    return ~(0xffffffffffffffffULL >> (uint32_t)prefix);
}

static uint64_t net_mask_lo(uint8_t prefix)
{
  if (prefix <= 64U)
    return 0ULL;
  else if (prefix >= 128U)
    return 0xffffffffffffffffULL;
  else
  {
    uint8_t lo_bits = (uint32_t)prefix - 64U;
    return ~(0xffffffffffffffffULL >> (uint32_t)lo_bits);
  }
}

static bool get_direction(uint64_t host_hi, uint64_t host_lo, uint32_t bit_pos)
{
  if (bit_pos < 64U)
  {
    uint32_t shift = 63U - bit_pos;
    return !((host_hi & 1ULL << shift) == 0ULL);
  }
  else
  {
    uint32_t adj = bit_pos - 64U;
    uint32_t shift = 63U - adj;
    return !((host_lo & 1ULL << shift) == 0ULL);
  }
}

static bool is_in_mask(uint32_t bit_pos, uint64_t mask_hi, uint64_t mask_lo)
{
  if (bit_pos < 64U)
  {
    uint32_t shift = 63U - bit_pos;
    return !((mask_hi & 1ULL << shift) == 0ULL);
  }
  else
  {
    uint32_t adj = bit_pos - 64U;
    uint32_t shift = 63U - adj;
    return !((mask_lo & 1ULL << shift) == 0ULL);
  }
}

FStar_Pervasives_Native_option___NRadixPulse_node_t_
NRadixPulse_null_tree_ptr = { .tag = FStar_Pervasives_Native_None };

FStar_Pervasives_Native_option___NRadixPulse_node_t_ NRadixPulse_create(void)
{
  NRadixPulse_node_t *root = KRML_HOST_MALLOC(sizeof (NRadixPulse_node_t));
  if (root != NULL)
    root[0U] =
      (
        (NRadixPulse_node_t){
          .has_value = false,
          .value = NetworkTypes_mk_ipnet(NetworkTypes_null_address, 0U),
          .left = NRadixPulse_null_tree_ptr,
          .right = NRadixPulse_null_tree_ptr
        }
      );
  return
    (
      (FStar_Pervasives_Native_option___NRadixPulse_node_t_){
        .tag = FStar_Pervasives_Native_Some,
        .v = root
      }
    );
}

void NRadixPulse_destroy_subtree(FStar_Pervasives_Native_option___NRadixPulse_node_t_ ct)
{
  if (!(ct.tag == FStar_Pervasives_Native_None))
    if (ct.tag == FStar_Pervasives_Native_Some)
    {
      NRadixPulse_node_t *p = ct.v;
      NRadixPulse_node_t n = *p;
      NRadixPulse_destroy_subtree(n.left);
      NRadixPulse_destroy_subtree(n.right);
      KRML_HOST_FREE(p);
    }
    else
    {
      KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
        __FILE__,
        __LINE__,
        "unreachable (pattern matches are exhaustive in F*)");
      KRML_HOST_EXIT(255U);
    }
}

void NRadixPulse_destroy(FStar_Pervasives_Native_option___NRadixPulse_node_t_ t)
{
  NRadixPulse_destroy_subtree(t);
}

static bool
uu___is_None___NRadixPulse_node_t_(
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ projectee
)
{
  if (projectee.tag == FStar_Pervasives_Native_None)
    return true;
  else
    return false;
}

bool NRadixPulse_is_empty(FStar_Pervasives_Native_option___NRadixPulse_node_t_ t)
{
  if (t.tag == FStar_Pervasives_Native_None)
    return true;
  else if (t.tag == FStar_Pervasives_Native_Some)
  {
    NRadixPulse_node_t *p = t.v;
    NRadixPulse_node_t n = *p;
    return
      !n.has_value && uu___is_None___NRadixPulse_node_t_(n.left) &&
        uu___is_None___NRadixPulse_node_t_(n.right);
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

NRadixSpec_find_result
NRadixPulse_find_walk(
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ ct,
  uint64_t host_hi,
  uint64_t host_lo,
  uint64_t mask_hi,
  uint64_t mask_lo,
  uint8_t remaining,
  NRadixSpec_find_result best
)
{
  if (ct.tag == FStar_Pervasives_Native_None)
    return best;
  else if (ct.tag == FStar_Pervasives_Native_Some)
  {
    NRadixPulse_node_t *p = ct.v;
    NRadixPulse_node_t n = *p;
    NRadixSpec_find_result best_;
    if (n.has_value)
      best_ = ((NRadixSpec_find_result){ .found = true, .net = n.value });
    else
      best_ = best;
    if (remaining == 0U)
      return best_;
    else
    {
      uint8_t remaining_ = (uint32_t)remaining - 1U;
      uint8_t bit_pos = 128U - (uint32_t)remaining;
      uint32_t bp = (uint32_t)bit_pos;
      if (!is_in_mask(bp, mask_hi, mask_lo))
        return best_;
      else
      {
        bool go_right = get_direction(host_hi, host_lo, bp);
        if (go_right)
          return
            NRadixPulse_find_walk(n.right,
              host_hi,
              host_lo,
              mask_hi,
              mask_lo,
              remaining_,
              best_);
        else
          return
            NRadixPulse_find_walk(n.left,
              host_hi,
              host_lo,
              mask_hi,
              mask_lo,
              remaining_,
              best_);
      }
    }
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

NRadixSpec_find_result
NRadixPulse_find(
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ t,
  NetworkTypes_ipnet net
)
{
  if (net.prefix == 0U)
    return
      (
        (NRadixSpec_find_result){
          .found = false,
          .net = NetworkTypes_mk_ipnet(NetworkTypes_null_address, 0U)
        }
      );
  else
  {
    uint64_t host_hi = bswap64(net.addr.hi);
    uint64_t host_lo = bswap64(net.addr.lo);
    uint64_t mask_hi = net_mask_hi(net.prefix);
    uint64_t mask_lo = net_mask_lo(net.prefix);
    return
      NRadixPulse_find_walk(t,
        host_hi,
        host_lo,
        mask_hi,
        mask_lo,
        128U,
        (
          (NRadixSpec_find_result){
            .found = false,
            .net = NetworkTypes_mk_ipnet(NetworkTypes_null_address, 0U)
          }
        ));
  }
}

NRadixSpec_find_result
NRadixPulse_find_addr(
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ t,
  NetworkTypes_address a
)
{
  uint8_t ite;
  if (a.family == NetworkTypes_FamilyIPv4)
    ite = 32U;
  else
    ite = 128U;
  NetworkTypes_ipnet net = NetworkTypes_mk_ipnet(a, ite);
  return NRadixPulse_find(t, net);
}

FStar_Pervasives_Native_option___NRadixPulse_node_t_
NRadixPulse_place_value_leaf(NetworkTypes_ipnet net)
{
  NRadixPulse_node_t *b = KRML_HOST_MALLOC(sizeof (NRadixPulse_node_t));
  if (b != NULL)
    b[0U] =
      (
        (NRadixPulse_node_t){
          .has_value = true,
          .value = net,
          .left = NRadixPulse_null_tree_ptr,
          .right = NRadixPulse_null_tree_ptr
        }
      );
  return
    (
      (FStar_Pervasives_Native_option___NRadixPulse_node_t_){
        .tag = FStar_Pervasives_Native_Some,
        .v = b
      }
    );
}

FStar_Pervasives_Native_option___NRadixPulse_node_t_
NRadixPulse_place_value_node(
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ ct,
  NRadixPulse_node_t *p,
  NetworkTypes_ipnet net
)
{
  NRadixPulse_node_t n = *p;
  if (n.has_value)
    return ct;
  else
  {
    *p =
      ((NRadixPulse_node_t){ .has_value = true, .value = net, .left = n.left, .right = n.right });
    return ct;
  }
}

FStar_Pervasives_Native_option___NRadixPulse_node_t_
NRadixPulse_insert_walk(
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ ct,
  NetworkTypes_ipnet net,
  uint64_t host_hi,
  uint64_t host_lo,
  uint64_t mask_hi,
  uint64_t mask_lo,
  uint8_t remaining
)
{
  if (ct.tag == FStar_Pervasives_Native_None)
    if (remaining == 0U)
      return NRadixPulse_place_value_leaf(net);
    else
    {
      uint8_t remaining_ = (uint32_t)remaining - 1U;
      uint8_t bit_pos = 128U - (uint32_t)remaining;
      uint32_t bp = (uint32_t)bit_pos;
      if (!is_in_mask(bp, mask_hi, mask_lo))
        return NRadixPulse_place_value_leaf(net);
      else
      {
        bool go_right = get_direction(host_hi, host_lo, bp);
        if (go_right)
        {
          FStar_Pervasives_Native_option___NRadixPulse_node_t_
          new_right =
            NRadixPulse_insert_walk(NRadixPulse_null_tree_ptr,
              net,
              host_hi,
              host_lo,
              mask_hi,
              mask_lo,
              remaining_);
          NRadixPulse_node_t *b = KRML_HOST_MALLOC(sizeof (NRadixPulse_node_t));
          if (b != NULL)
            b[0U] =
              (
                (NRadixPulse_node_t){
                  .has_value = false,
                  .value = NetworkTypes_mk_ipnet(NetworkTypes_null_address, 0U),
                  .left = NRadixPulse_null_tree_ptr,
                  .right = new_right
                }
              );
          return
            (
              (FStar_Pervasives_Native_option___NRadixPulse_node_t_){
                .tag = FStar_Pervasives_Native_Some,
                .v = b
              }
            );
        }
        else
        {
          FStar_Pervasives_Native_option___NRadixPulse_node_t_
          new_left =
            NRadixPulse_insert_walk(NRadixPulse_null_tree_ptr,
              net,
              host_hi,
              host_lo,
              mask_hi,
              mask_lo,
              remaining_);
          NRadixPulse_node_t *b = KRML_HOST_MALLOC(sizeof (NRadixPulse_node_t));
          if (b != NULL)
            b[0U] =
              (
                (NRadixPulse_node_t){
                  .has_value = false,
                  .value = NetworkTypes_mk_ipnet(NetworkTypes_null_address, 0U),
                  .left = new_left,
                  .right = NRadixPulse_null_tree_ptr
                }
              );
          return
            (
              (FStar_Pervasives_Native_option___NRadixPulse_node_t_){
                .tag = FStar_Pervasives_Native_Some,
                .v = b
              }
            );
        }
      }
    }
  else if (ct.tag == FStar_Pervasives_Native_Some)
  {
    NRadixPulse_node_t *p = ct.v;
    NRadixPulse_node_t n = *p;
    if (remaining == 0U)
      if (n.has_value)
        return ct;
      else
      {
        *p =
          (
            (NRadixPulse_node_t){
              .has_value = true,
              .value = net,
              .left = n.left,
              .right = n.right
            }
          );
        return ct;
      }
    else
    {
      uint8_t remaining_ = (uint32_t)remaining - 1U;
      uint8_t bit_pos = 128U - (uint32_t)remaining;
      uint32_t bp = (uint32_t)bit_pos;
      if (!is_in_mask(bp, mask_hi, mask_lo))
        if (n.has_value)
          return ct;
        else
        {
          *p =
            (
              (NRadixPulse_node_t){
                .has_value = true,
                .value = net,
                .left = n.left,
                .right = n.right
              }
            );
          return ct;
        }
      else
      {
        bool go_right = get_direction(host_hi, host_lo, bp);
        if (go_right)
        {
          FStar_Pervasives_Native_option___NRadixPulse_node_t_
          new_right =
            NRadixPulse_insert_walk(n.right,
              net,
              host_hi,
              host_lo,
              mask_hi,
              mask_lo,
              remaining_);
          *p =
            (
              (NRadixPulse_node_t){
                .has_value = n.has_value,
                .value = n.value,
                .left = n.left,
                .right = new_right
              }
            );
          return ct;
        }
        else
        {
          FStar_Pervasives_Native_option___NRadixPulse_node_t_
          new_left =
            NRadixPulse_insert_walk(n.left,
              net,
              host_hi,
              host_lo,
              mask_hi,
              mask_lo,
              remaining_);
          *p =
            (
              (NRadixPulse_node_t){
                .has_value = n.has_value,
                .value = n.value,
                .left = new_left,
                .right = n.right
              }
            );
          return ct;
        }
      }
    }
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

FStar_Pervasives_Native_option___NRadixPulse_node_t_
NRadixPulse_insert(
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ t,
  NetworkTypes_ipnet net
)
{
  if (net.prefix == 0U)
    return t;
  else if (net.prefix > 128U)
    return t;
  else
  {
    uint64_t host_hi = bswap64(net.addr.hi);
    uint64_t host_lo = bswap64(net.addr.lo);
    uint64_t mask_hi = net_mask_hi(net.prefix);
    uint64_t mask_lo = net_mask_lo(net.prefix);
    FStar_Pervasives_Native_option___NRadixPulse_node_t_
    new_root = NRadixPulse_insert_walk(t, net, host_hi, host_lo, mask_hi, mask_lo, 128U);
    return new_root;
  }
}

NRadixPulse_insert_result
NRadixPulse_try_insert(
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ t,
  NetworkTypes_ipnet net
)
{
  NRadixSpec_find_result existing = NRadixPulse_find(t, net);
  bool was_dup = existing.found && existing.net.prefix == net.prefix;
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ new_t = NRadixPulse_insert(t, net);
  return ((NRadixPulse_insert_result){ .tree = new_t, .inserted = !was_dup });
}

