/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/ghutton/code/go/src/github.com/FStarLang/FStar/karamel/krml -skip-linking -backend c -warn-error -2-15 -minimal -tmpdir extracted -bundle NetworkTypes -bundle NRadixPulse=NRadixPulse,NRadixSpec,FStar.Pervasives.Native out_NRadixPulse.krml
  F* version: <unknown>
  KaRaMeL version: 772e4f63642524f6fb3c15fcb1b9398dd6afea7f
 */

#ifndef NRadixPulse_H
#define NRadixPulse_H

#include "NetworkTypes.h"

typedef struct NRadixSpec_find_result_s
{
  bool found;
  NetworkTypes_ipnet net;
}
NRadixSpec_find_result;

typedef struct NRadixPulse_node_t_s NRadixPulse_node_t;

#define FStar_Pervasives_Native_None 0
#define FStar_Pervasives_Native_Some 1

typedef uint8_t FStar_Pervasives_Native_option___NRadixPulse_node_t__tags;

typedef struct FStar_Pervasives_Native_option___NRadixPulse_node_t__s
{
  FStar_Pervasives_Native_option___NRadixPulse_node_t__tags tag;
  NRadixPulse_node_t *v;
}
FStar_Pervasives_Native_option___NRadixPulse_node_t_;

typedef struct NRadixPulse_node_t_s
{
  bool has_value;
  NetworkTypes_ipnet value;
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ left;
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ right;
}
NRadixPulse_node_t;

typedef NRadixPulse_node_t *NRadixPulse_node_box;

typedef FStar_Pervasives_Native_option___NRadixPulse_node_t_ NRadixPulse_tree_ptr;

typedef struct NRadixPulse_pulse_find_result_s
{
  bool found;
  NetworkTypes_ipnet net;
}
NRadixPulse_pulse_find_result;

typedef FStar_Pervasives_Native_option___NRadixPulse_node_t_ NRadixPulse_nradix_tree;

extern FStar_Pervasives_Native_option___NRadixPulse_node_t_ NRadixPulse_null_tree_ptr;

FStar_Pervasives_Native_option___NRadixPulse_node_t_ NRadixPulse_create(void);

void NRadixPulse_destroy_subtree(FStar_Pervasives_Native_option___NRadixPulse_node_t_ ct);

void NRadixPulse_destroy(FStar_Pervasives_Native_option___NRadixPulse_node_t_ t);

bool NRadixPulse_is_empty(FStar_Pervasives_Native_option___NRadixPulse_node_t_ t);

NRadixSpec_find_result
NRadixPulse_find_walk(
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ ct,
  uint64_t host_hi,
  uint64_t host_lo,
  uint64_t mask_hi,
  uint64_t mask_lo,
  uint8_t remaining,
  NRadixSpec_find_result best
);

NRadixSpec_find_result
NRadixPulse_find(
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ t,
  NetworkTypes_ipnet net
);

NRadixSpec_find_result
NRadixPulse_find_addr(
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ t,
  NetworkTypes_address a
);

FStar_Pervasives_Native_option___NRadixPulse_node_t_
NRadixPulse_place_value_leaf(NetworkTypes_ipnet net);

FStar_Pervasives_Native_option___NRadixPulse_node_t_
NRadixPulse_place_value_node(
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ ct,
  NRadixPulse_node_t *p,
  NetworkTypes_ipnet net
);

FStar_Pervasives_Native_option___NRadixPulse_node_t_
NRadixPulse_insert_walk(
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ ct,
  NetworkTypes_ipnet net,
  uint64_t host_hi,
  uint64_t host_lo,
  uint64_t mask_hi,
  uint64_t mask_lo,
  uint8_t remaining
);

FStar_Pervasives_Native_option___NRadixPulse_node_t_
NRadixPulse_insert(
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ t,
  NetworkTypes_ipnet net
);

typedef struct NRadixPulse_insert_result_s
{
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ tree;
  bool inserted;
}
NRadixPulse_insert_result;

NRadixPulse_insert_result
NRadixPulse_try_insert(
  FStar_Pervasives_Native_option___NRadixPulse_node_t_ t,
  NetworkTypes_ipnet net
);


#define NRadixPulse_H_DEFINED
#endif /* NRadixPulse_H */
