/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/ghutton/code/go/src/github.com/FStarLang/FStar/karamel/krml -skip-linking -backend c -warn-error -2-15 -minimal -tmpdir extracted -bundle NetworkTypes -bundle NRadixPulse=NRadixPulse,NRadixSpec,FStar.Pervasives.Native out_NRadixPulse.krml
  F* version: <unknown>
  KaRaMeL version: 772e4f63642524f6fb3c15fcb1b9398dd6afea7f
 */

#ifndef Prims_H
#define Prims_H

extern krml_checked_int_t Prims_op_Multiply(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Division(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Subtraction(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Addition(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Minus(krml_checked_int_t x0);

extern krml_checked_int_t Prims_op_Modulus(krml_checked_int_t x, krml_checked_int_t y);

extern bool Prims_op_LessThanOrEqual(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_GreaterThan(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_GreaterThanOrEqual(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_LessThan(krml_checked_int_t x0, krml_checked_int_t x1);

extern krml_checked_int_t Prims_pow2(krml_checked_int_t x0);

extern krml_checked_int_t Prims_abs(krml_checked_int_t x0);

extern Prims_string Prims_strcat(Prims_string x0, Prims_string x1);

extern Prims_string Prims_string_of_int(krml_checked_int_t x0);

typedef void *Prims_prop;


#define Prims_H_DEFINED
#endif /* Prims_H */
