name: Create support-package index.html
description: |
  Creates an index.html file by grabbing the latest version of support-packages
  uploaded to GCP for all supported architectures.

inputs:
  gcp-bucket:
    required: true
    description: |
      GCP bucket used for getting the latest versions of support-packages
  metadata-path:
    required: true
    description: |
      Path to generated collector metadata
  output-path:
    required: true
    description: |
      Path to generated artifacts

runs:
  using: composite
  steps:
  - name: Get latest support-packages
    shell: bash
    run: |
      for arch in x86_64 s390x ppc64le; do
        for version_path in ${{ inputs.metadata-path }}/module-versions/*; do
          version="$(basename "${version_path}")"
          output_dir="${{ inputs.output-path }}/${arch}/${version}"

          mkdir -p "${output_dir}"
          if ! gsutil cp "gs://${{ inputs.gcp-bucket }}/${arch}/${version}/latest" \
            "${output_dir}/latest"; then
            continue
          fi

          latest_pkg="$(cat "${output_dir}/latest")"

          touch "${output_dir}/${latest_pkg}"
          touch "${output_dir}/${latest_pkg}.sha256"
          touch "${output_dir}/support-pkg-${version}-latest.zip"
          touch "${output_dir}/support-pkg-${version}-latest.zip.sha256"
        done
      done

  - name: Create index file
    shell: bash
    run: |
      relative_path="collector/support-packages"

      if [[ "${{ github.event_name == 'pull_request' }}" == "true" ]]; then
          relative_path="${relative_path}/${GITHUB_HEAD_REF}/${{ github.run_id }}"
      fi

      DOWNLOAD_BASE_URL="https://install.stackrox.io"
      export BASE_URL="${DOWNLOAD_BASE_URL}/${relative_path}"

      ${{ github.workspace }}/kernel-modules/support-packages/05-create-index.py \
        ${{ inputs.metadata-path }} \
        ${{ inputs.output-path }}
