---

gcp_ssh_key_file: "{{ lookup('env', 'GCP_SSH_KEY_FILE', default='~/.ssh/google_compute_engine') }}"

ansible_ssh_private_key_file: "{{ gcp_ssh_key_file }}"

current_user: "{{ lookup('env', 'USER') }}"
job_id: "{{ lookup('env', 'JOB_ID', default=current_user) }}"
test_platform: "{{ lookup('env', 'VM_TYPE', default='rhel') }}"
collector_root: "{{ playbook_dir }}/.."
collector_test: "{{ lookup('env', 'COLLECTOR_TEST', default='ci-integration-tests') }}"

virtual_machines:
  - name: rhel
    project: rhel-cloud
    families:
      - rhel-7
      - rhel-8

  - name: rhel-sap
    project: rhel-sap-cloud
    families:
      - rhel-8-4-sap-ha
      - rhel-8-6-sap-ha

  - name: cos
    project: cos-cloud
    families:
      - cos-stable
      - cos-beta
      - cos-dev
      - cos-89-lts

  - name: sles
    project: suse-cloud
    families:
      - sles-12
      - sles-15

  - name: ubuntu-os
    project: ubuntu-os-cloud
    families:
      - ubuntu-1804-lts
      - ubuntu-2004-lts
      - ubuntu-2204-lts

  - name: ubuntu-os-pro
    project: ubuntu-os-pro-cloud
    families:
      - ubuntu-pro-1804-lts

  - name: flatcar
    project: kinvolk-public
    username: core
    families:
      - flatcar-stable

  - name: fedora-coreos
    project: fedora-coreos-cloud
    username: core
    families:
      - fedora-coreos-stable

  - name: garden-linux
    project: sap-se-gcp-gardenlinux
    images:
      - gardenlinux-gcp-cloud-gardener--prod-576-9-229156
