---
- name: Safely create GCP compute instance
  block:
    - name: Create compute instance
      google.cloud.gcp_compute_instance:
        name: "{{ vm_name }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_auth_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        zone: "{{ gcp_zone }}"
        machine_type: "{{ vm_machine_type | default('e2-standard-2') }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              disk_size_gb: "{{ vm_disk_size | default(20) }}"
              source_image: "{{ gcp_source_image }}"
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        labels: "{{ gcp_default_labels | combine(gcp_extra_labels) }}"
        metadata: "{{ gcp_meta_data | default({}) }}"
      register: instance_result
  rescue:
    - name: Remove failed GCP compute instance
      google.cloud.gcp_compute_instance:
        name: "{{ vm_name }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_auth_kind }}"
        service_account_file: "{{ gcp_service_account_file }}"
        zone: "{{ gcp_zone }}"
        state: absent
