---

- name: Create VMs From Image
  google.cloud.gcp_compute_instance:
    name: "{{ gcp_instance_prefix }}-{{ item.0.name }}-{{ job_id }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
    zone: "{{ gcp_zone }}"
    machine_type: e2-standard-2
    disks:
      - auto_delete: true
        boot: true
        initialize_params:
          disk_size_gb: 20
          source_image: "projects/{{ item.0.project }}/global/images/{{ item.1 }}"
    network_interfaces:
      - network: "default"
        access_configs:
          - name: External NAT
            type: ONE_TO_ONE_NAT
    labels:
      job_id: "{{ job_id }}"
      platform: "{{ item.0.name }}"
      vm_config: "{{ item.0.name }}_{{ item.0.name }}"
      username: "{{ item.0.username | default(gcp_default_user) }}"
