---

- name: Start docker service
  service:
    name: "docker"
    enabled: true
    state: started

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Reset SSH connection for group propagation
  meta: reset_connection
