---

- wait_for_connection:
    delay: 10
    timeout: 60

- name: Gather facts
  setup:

- debug: msg="{{ ansible_facts['os_family'] }}"

- name: RedHat Provisioning
  include_tasks: "redhat.yml"
  when: ansible_facts['os_family'] == 'RedHat'

- name: Ubuntu Provisioning
  include_tasks: "ubuntu.yml"
  when: ansible_facts['os_family'] == 'Ubuntu' or ansible_facts['os_family'] == 'Debian'

- name: Start docker service
  service:
    name: "docker"
    enabled: true
    state: started

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

