---

#
# Provisioning takes place once the VM is created. We need to handle a number
# of platforms here, and the ordering of this logic is quite important
# for the Container OS platforms like flatcar and fedora-coreos.
#
# For those platforms, Python does not exist (which is a requirement for 
# ansible) so it is installed first, before the rest of the provisioning
# continues.
#

- set_fact:
    is_coreos: "{{ vm_config.find('coreos') != -1 | bool }}"

- include_tasks: "fedora-coreos.yml"
  when: is_coreos


# At this point, ansible should be able to run on the remote host

- wait_for_connection:
    delay: 10
    timeout: 60

- name: Gather facts
  setup:

- name: RedHat Provisioning
  include_tasks: "redhat.yml"
  when: ansible_facts['os_family'] == 'RedHat' and not is_coreos

- name: Ubuntu Provisioning
  include_tasks: "ubuntu.yml"
  when: ansible_facts['os_family'] == 'Ubuntu' or ansible_facts['os_family'] == 'Debian'

# Common logic after this point must be able to run on all platforms.

- name: Start docker service
  service:
    name: "docker"
    enabled: true
    state: started

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

