---

- name: Create GCP VMs
  hosts: localhost
  vars:
    platform: "{{ lookup('env', 'TEST_PLATFORM') | default('all') }}"

  tasks:
    - name: Include VM definitions
      include_vars:
        file: instances.yml
        name: instances

    - name: Create VM network
      google.cloud.gcp_compute_network:
        name: "collector-osci-network-{{ instances.job_id }}"
        project: "{{ instances.gcp_project }}"
        auth_kind: "{{ instances.gcp_auth_kind }}"
        auto_create_subnetworks: true
        state: present
      register: gcp_network

    - name: Create VMs From Family
      google.cloud.gcp_compute_instance:
        name: "collector-osci-{{ item.1 }}"
        project: "{{ instances.gcp_project }}"
        auth_kind: "{{ instances.gcp_auth_kind }}"
        zone: "{{ instances.gcp_zone }}"
        machine_type: e2-standard-2
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              disk_size_gb: 20
              source_image: "projects/{{ item.0.project }}/global/images/family/{{ item.1 }}"
        network_interfaces:
          - network: "{{ network }}"
      loop: "{{ instances.virtual_machines | subelements('families', skip_missing=True) }}"
      when: "{{ platform }} == {{ item.0.name }} || {{ platform }} == all"

    - name: Create VMs From Image
      google.cloud.gcp_compute_instance:
        name: "collector-osci-{{ item.0.name }}"
        project: "{{ instances.gcp_project }}"
        auth_kind: "{{ instances.gcp_auth_kind }}"
        zone: "{{ instances.gcp_zone }}"
        machine_type: e2-standard-2
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              disk_size_gb: 20
              source_image: "projects/{{ item.0.project }}/global/images/{{ item.1 }}"
        network_interfaces:
          - network: "{{ network }}"
      loop: "{{ instances.virtual_machines | subelements('images', skip_missing=True) }}"
      when: "{{ platform }} == {{ item.0.name }} || {{ platform }} == all"
