---
- name: Delete VMs
  hosts: "job_id_{{ lookup('env', 'JOB_ID', default='1') }}"
  gather_facts: false
  tasks:
    - name: Include Configuration
      include_vars:
        file: instances.yml
        name: instances

    - name: Delete VMs
      delegate_to: localhost
      google.cloud.gcp_compute_instance:
        name: "{{ inventory_hostname }}"
        project: "{{ instances.gcp_project }}"
        auth_kind: "{{ instances.gcp_auth_kind }}"
        zone: "{{ instances.gcp_zone }}"
        state: absent

