---

plugin: gcp_compute
projects:
  # this means the inventory will look for VMs in both projects
  # but does not mean it will necessarily find any.
  #
  # For use in CI, our VMs will exist in stackrox-ci, but we can
  # also create them in stackrox-dev for more ad-hoc testing
  - stackrox-dev
  - stackrox-ci
filters:
  - name = collector-osci-giles-*
keyed_groups:
  # This will group the VMs by their labels, which means that on
  # creation, we can use a unique identifier to group VMs 
  # based on Job ID, to avoid running on all CI VMs or on 
  # specific platforms (for the provisioning playbooks)
  - prefix: job_id
    key: labels.job_id

  - prefix: platform
    key: labels.platform
auth_kind: application
hostnames:
  - name
compose:
  # use the public IP as the ansible host for SSH
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
  ansible_user: labels.username
  ansible_port: 22
  vm_config: labels.vm_config
