/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/ghutton/code/go/src/github.com/FStarLang/FStar/karamel/krml -skip-linking -backend c -warn-error -2-15 -minimal -tmpdir extracted -bundle NetworkTypes -bundle NRadixPulse=NRadixPulse,NRadixSpec,FStar.Pervasives.Native out_NRadixPulse.krml
  F* version: <unknown>
  KaRaMeL version: 772e4f63642524f6fb3c15fcb1b9398dd6afea7f
 */

#ifndef internal_NetworkTypes_H
#define internal_NetworkTypes_H

#include "../NetworkTypes.h"

extern NetworkTypes_address NetworkTypes_null_address;

NetworkTypes_ipnet NetworkTypes_mk_ipnet(NetworkTypes_address addr, uint8_t prefix);


#define internal_NetworkTypes_H_DEFINED
#endif /* internal_NetworkTypes_H */
