FROM ubuntu:14.04

# SYSDIG_HOST_ROOT is required by the sysdig kernel module; used as a prefix to
# paths like /dev/sysdig0, /proc, and /boot. Make sure this matches the volume
# mount paths used when launching this container.
#
# COLLECTOR_CONFIG is the required json config string, and it defaults to
# { "syscalls": [],"topic_query_field": "" }
#
# MAX_CONTENT_LENGTH_KB is optional, and it defaults to 1024.
#
# CONNECTION_LIMIT is optional, and it defaults to 64.
#
# CONNECTION_LIMIT_PER_IP is optional, and it defaults to 64.
#
# CONNECTION_TIMEOUT is optional, and it defaults to 8.
#
ENV SYSDIG_HOST_ROOT=/host \
    MAX_CONTENT_LENGTH_KB=1024 \
    CONNECTION_LIMIT=64 \
    CONNECTION_LIMIT_PER_IP=64 \
    CONNECTION_TIMEOUT=8 \
    CHISEL='LS0gQ2hpc2VsIGRlc2NyaXB0aW9uCmRlc2NyaXB0aW9uID0gIm9ubHkgZGlzcGxheSBldmVudHMgcmVsZXZhbnQgdG8gc2VjdXJpdHkgbW9kZWxpbmcgYW5kIGRldGVjdGlvbiIKc2hvcnRfZGVzY3JpcHRpb24gPSAic2VjdXJpdHkgcmVsZXZhbnQiCmNhdGVnb3J5ID0gIm1pc2MiCgotLSBDaGlzZWwgYXJndW1lbnQgbGlzdAphcmdzID0ge30KCi0tIEV2ZW50IHBhcnNpbmcgY2FsbGJhY2sKZnVuY3Rpb24gb25fZXZlbnQoKQogICAgcmV0dXJuIHRydWUKZW5kCgpmdW5jdGlvbiBvbl9pbml0KCkKICAgIGZpbHRlciA9ICJub3QgY29udGFpbmVyLmlkID0gJ2hvc3QnXG4iCiAgICBjaGlzZWwuc2V0X2ZpbHRlcihmaWx0ZXIpCiAgICByZXR1cm4gdHJ1ZQplbmQK'

# HTTP API port (4419)
EXPOSE 4419

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        gcc-4.8 \
        g++-4.8 \
        jq \
        libboost-regex-dev \
        libjsoncpp0 \
        libmicrohttpd10 \
        libssl1.0.0 \
        procps \
        debian-keyring \
        debian-archive-keyring \
        wget \
    && apt-get clean \
    ;

# Update Debian signing keys, which are required to get old kernels from Jessie.
RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak && \
  echo "deb http://ftp.us.debian.org/debian jessie main" > /etc/apt/sources.list && \
  apt-get update && \
  apt-get install -y debian-keyring debian-archive-keyring && \
  rm /etc/apt/sources.list && \
  mv /etc/apt/sources.list.bak /etc/apt/sources.list

COPY bin/curl /usr/local/bin/curl
COPY bin/collector /usr/local/bin/collector
COPY libs/librdkafka.so /usr/local/lib/librdkafka.so
COPY libs/libcurl.so /usr/local/lib/libcurl.so
COPY libs/libsysdignative.so /usr/local/lib/libsysdignative.so

# `ldconfig` is required so that `curl` can find its `libcurl.so`.
RUN ldconfig

WORKDIR /

# update boot script
COPY scripts/bootstrap.sh /bootstrap.sh
RUN chown root.root /bootstrap.sh
RUN chmod 700 /bootstrap.sh

# copy notice and license files
COPY NOTICE.txt /NOTICE.txt
COPY COPYING-GPLv2.txt /COPYING-GPLv2.txt
COPY COPYING-LGPLv2.1.txt /COPYING-LGPLv2.1.txt

ENTRYPOINT ["/bootstrap.sh"]

# You must provide a BROKER_LIST environment variable or override the CMD.
# For information on other variables, see the explanations of these environment variables above.
CMD collector \
        --collector-config=$COLLECTOR_CONFIG \
        --chisel=$CHISEL \
        --broker-list=$BROKER_LIST \
        --max-content-length=$MAX_CONTENT_LENGTH_KB \
        --connection-limit=$CONNECTION_LIMIT \
        --per-ip-connection-limit=$CONNECTION_LIMIT_PER_IP \
        --connection-timeout=$CONNECTION_TIMEOUT
