ARG BASE_REGISTRY=registry.access.redhat.com
ARG BASE_IMAGE=ubi7/ubi
ARG BASE_TAG=7.7

ARG collector_builder_tag
FROM stackrox/collector-builder:${collector_builder_tag} as builder

FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG}

ARG collector_version=xxx
ARG module_version=xxx

LABEL maintainer="StackRox <support@stackrox.com>"
LABEL io.stackrox.collector.module-version="${module_version}"

ENV MODULE_VERSION=${module_version}

RUN yum update -y --disableplugin=subscription-manager && \
    rpm -e --nodeps yum yum-utils yum-plugin-ovl subscription-manager rpm rpm-libs rpm-build-libs rpm-python subscription-manager-rhsm

# Add module version file only
RUN mkdir /kernel-modules && \
    echo "${module_version}" >/kernel-modules/MODULE_VERSION.txt

ENV COLLECTOR_HOST_ROOT=/host

# HTTP API port (8080)
EXPOSE 8080 9090

COPY libs/libsinsp-wrapper.so.rhel \
     /usr/local/lib/libsinsp-wrapper.so

WORKDIR /

# Uncomment below when Address Sanitizer needs to be enabled for collector

# RUN apt-get update && apt-get install -y --no-install-recommends llvm && apt-get clean
# ENV ASAN_SYMBOLIZER_PATH /usr/bin/llvm-symbolizer-3.4
# ENV ASAN_OPTIONS symbolize=1:disable_core=0:abort_on_error=1:unmap_shadow_on_exit=1

# Uncomment below line when volume needs to created for extracting the Collector core
# VOLUME ["/core"]

# update boot script
COPY scripts/bootstrap.sh /bootstrap.sh
COPY scripts/collector-wrapper.sh /usr/local/bin/
RUN chown root.root /bootstrap.sh
RUN chmod 700 /bootstrap.sh

# copy notice and license files
COPY NOTICE-collector.txt \
     COPYING.txt \
     /

ENTRYPOINT ["/bootstrap.sh"]

CMD collector-wrapper.sh \
    --collector-config=$COLLECTOR_CONFIG \
    --collection-method=$COLLECTION_METHOD \
    --grpc-server=$GRPC_SERVER

COPY bin/collector.rhel /usr/local/bin/collector

# RHEL7 needs a newer version of curl and gzip
COPY --from=builder /usr/local/bin/curl /usr/bin/curl
COPY --from=builder /usr/local/lib/libcurl.so.4 /lib64/libcurl.so.4
COPY --from=builder /usr/local/bin/gzip /usr/bin/gzip

LABEL io.stackrox.collector.version="${collector_version}"
ENV COLLECTOR_VERSION=${collector_version}

HEALTHCHECK CMD curl --fail http://localhost:8080/ready || exit 1
