ARG base=latest
# This is a hack because the argument to FROM must be either a hardcoded string or a variable expansion, but not a
# mix of both.
ARG base_image=stackrox/kernel-modules:${base}

FROM ${base_image} AS kernel_modules

FROM debian:stretch-slim

MAINTAINER StackRox <support@stackrox.com>

# Add module version file only 
RUN mkdir /kernel-modules
COPY --from=kernel_modules /kernel-modules/MODULE_VERSION.txt /kernel-modules/

# SYSDIG_HOST_ROOT is required by the sysdig kernel module; used as a prefix to
# paths like /dev/sysdig0, /proc, and /boot. Make sure this matches the volume
# mount paths used when launching this container.
#
ENV SYSDIG_HOST_ROOT=/host

# HTTP API port (8080)
EXPOSE 8080 9090

RUN apt-get update \
 && apt-get upgrade -y \
 && apt-get install -y --no-install-recommends \
        ca-certificates \
        kmod \
        curl \
        libcurl3 \
        openssl \
        libuuid1 \
        libcap-ng0 \
        libb64-0d \
        jq \
        libluajit-5.1 \
        libtbb2 \
        libelf1 \
        libjsoncpp1 \
 ;
dpkg -r --force-all e2fslibs e2fsprogs apt debconf dpkg \
 && rm -rf /var/lib/apt /var/lib/dpkg \
 ;

COPY libs/libsinsp-wrapper.so \
     /usr/local/lib/

WORKDIR /

# Uncomment below when Address Sanitizer needs to be enabled for collector

# RUN apt-get update && apt-get install -y --no-install-recommends llvm && apt-get clean
# ENV ASAN_SYMBOLIZER_PATH /usr/bin/llvm-symbolizer-3.4
# ENV ASAN_OPTIONS symbolize=1:disable_core=0:abort_on_error=1:unmap_shadow_on_exit=1

# Uncomment below line when volume needs to created for extracting the Collector core
# VOLUME ["/core"]

# update boot script
COPY scripts/bootstrap.sh /bootstrap.sh
RUN chown root.root /bootstrap.sh
RUN chmod 700 /bootstrap.sh

# copy notice and license files
COPY NOTICE-collector.txt \
     COPYING.txt \
     /

ENTRYPOINT ["/bootstrap.sh"]

CMD collector \
    --collector-config=$COLLECTOR_CONFIG \
    --collection-method=$COLLECTION_METHOD \
    --grpc-server=$GRPC_SERVER

COPY bin/ /usr/local/bin/
