ARG collector_builder_tag
FROM stackrox/collector-builder:${collector_builder_tag} as builder

FROM registry.access.redhat.com/ubi7/ubi

ARG collector_version=xxx
ARG module_version=xxx

LABEL maintainer="StackRox <support@stackrox.com>"
LABEL io.stackrox.collector.module-version="${module_version}"

ENV MODULE_VERSION=${module_version}

# Make image STIG compliant: https://dccscr.dsop.io/dsop/redhat/ubi/ubi7/
ARG DSOP_URL=https://dccscr.dsop.io/dsop/redhat/ubi/ubi7/raw/18d21ee5ed843e7b319e2670f47687f057db98a6/7.7
RUN ( for i in dsop-fix-{1,2,3}.sh ; do curl -O "$DSOP_URL/$i" ; done; )
RUN ( chmod +x /dsop-fix-{1,2}.sh && for i in $(ls /dsop-fix-{1,2}.sh); do sh ${i}; done; )
RUN ( yum update -y --disableplugin=subscription-manager && rm -rf /var/cache/yum/ /var/tmp/* /tmp/* /var/tmp/.???* /tmp/.???*; )
RUN ( chmod +x /dsop-fix-3.sh && for i in $(ls /dsop-fix-3.sh); do sh ${i}; done && rm -rf /dsop-fix*.sh ; )

# Remove package manager
RUN rpm -e --nodeps yum yum-utils yum-plugin-ovl subscription-manager rpm rpm-libs rpm-build-libs rpm-python subscription-manager-rhsm

# Add module version file only
RUN mkdir /kernel-modules && \
    echo "${module_version}" >/kernel-modules/MODULE_VERSION.txt

# SYSDIG_HOST_ROOT is required by the sysdig kernel module; used as a prefix to
# paths like /dev/sysdig0, /proc, and /boot. Make sure this matches the volume
# mount paths used when launching this container.
#
ENV SYSDIG_HOST_ROOT=/host

# HTTP API port (8080)
EXPOSE 8080 9090

COPY libs/libsinsp-wrapper.so.rhel \
     /usr/local/lib/libsinsp-wrapper.so

WORKDIR /

# Uncomment below when Address Sanitizer needs to be enabled for collector

# RUN apt-get update && apt-get install -y --no-install-recommends llvm && apt-get clean
# ENV ASAN_SYMBOLIZER_PATH /usr/bin/llvm-symbolizer-3.4
# ENV ASAN_OPTIONS symbolize=1:disable_core=0:abort_on_error=1:unmap_shadow_on_exit=1

# Uncomment below line when volume needs to created for extracting the Collector core
# VOLUME ["/core"]

# update boot script
COPY scripts/bootstrap.sh /bootstrap.sh
RUN chown root.root /bootstrap.sh
RUN chmod 700 /bootstrap.sh

# copy notice and license files
COPY NOTICE-collector.txt \
     COPYING.txt \
     /

ENTRYPOINT ["/bootstrap.sh"]

CMD collector \
    --collector-config=$COLLECTOR_CONFIG \
    --collection-method=$COLLECTION_METHOD \
    --grpc-server=$GRPC_SERVER

COPY bin/collector.rhel /usr/local/bin/collector

# RHEL7 needs a newer version of curl and gzip
COPY --from=builder /usr/local/bin/curl /usr/bin/curl
COPY --from=builder /usr/local/lib/libcurl.so.4 /lib64/libcurl.so.4
COPY --from=builder /usr/local/bin/gzip /usr/bin/gzip

LABEL io.stackrox.collector.version="${collector_version}"
ENV COLLECTOR_VERSION=${collector_version}
