restart_interval = 10
workers = 1
per_core = false

[workload]
type = "network"
server = true
address = "223.42.0.1"
target_port = 1337
connections_static = 0
connections_dyn_max = 20
preempt = false
conns_per_addr = 1
