#!/bin/sh
set -e

fatal() {
    echo "Fatal: $*" 1>&2
    exit 1
}

[ -n "$CIRCLE_NODE_TOTAL" ] || fatal "No parallelism."

[ -n "$CIRCLE_NODE_INDEX" ] || fatal "No parallelism."

[ "$CIRCLE_NODE_TOTAL" -eq 9 ] || fatal "Bad parallelism node count."

case "$CIRCLE_NODE_INDEX" in
    0)
        echo "Running parallel job as node 1/9."
        echo "Building CoreOS kernel modules."
        exec make -C kernel-modules build-coreos
        ;;

    1)
        echo "Running parallel job as node 2/9."
        echo "Building CentOS kernel modules."
        exec make -C kernel-modules build-centos
        ;;

    2)
        echo "Running parallel job as node 3/9."
        echo "Building CentOS (uncrawled) kernel modules, 1/2."
        ./scripts/partition kernel-modules/supported-kernels/centos-uncrawled.txt 2 0
        exec make -C kernel-modules build-centos-uncrawled
        ;;

    3)
        echo "Running parallel job as node 4/9."
        echo "Building CentOS (uncrawled) kernel modules, 2/2."
        ./scripts/partition kernel-modules/supported-kernels/centos-uncrawled.txt 2 1
        exec make -C kernel-modules build-centos-uncrawled
        ;;

    4)
        echo "Running parallel job as node 5/9."
        echo "Building Ubuntu (AWS) kernel modules."
        exec make -C kernel-modules build-ubuntu-aws
        ;;

    5)
        echo "Running parallel job as node 6/9."
        echo "Building Ubuntu (Azure) kernel modules."
        exec make -C kernel-modules build-ubuntu-azure
        ;;

    6)
        echo "Running parallel job as node 7/9."
        echo "Building Ubuntu (GCP) kernel modules."
        exec make -C kernel-modules build-ubuntu-gcp
        ;;

    7)
        echo "Running parallel job as node 8/9."
        echo "Building Ubuntu (GKE) kernel modules."
        exec make -C kernel-modules build-ubuntu-gke
        ;;

    8)
        echo "Running parallel job as node 9/9."
        echo "Building Ubuntu (Standard) kernel modules."
        exec make -C kernel-modules build-ubuntu-standard
        ;;

esac

fatal "Bad parallelism node index."
