#!/bin/sh
set -eu

copy() {
    source_file="$1"
    destination_file="$2"

    echo "START copying [$source_file] to [$destination_file]"
    gsutil cp "$source_file" "$destination_file"
    echo "DONE copying [$source_file] to [$destination_file]"
}

main() {
    bucket_prefix="$1"
    directory_prefix="$2"
    list_file="$3"

    echo "list stored in: $list_file"

    while IFS="" read -r line; do
        source_file="${bucket_prefix}/${line}"
        destination_file="${directory_prefix}/${line}"

        echo "Copying $source_file to $destination_file"
        copy "$source_file" "$destination_file" &
    done < "$list_file"

    wait
}

main "$@"