#!/bin/sh
set -e

fatal() {
    echo "Fatal: $*" 1>&2
    exit 1
}

file="$1"
count="$2"
target="$3"

[ -n "$file" ]   || fatal "No file given."
[ -n "$count" ]  || fatal "No count given."
[ -n "$target" ] || fatal "No target given."

contents="$(cat "$file")"

index=0

echo "$contents" | while IFS='' read -r line || [ -n "$line" ]; do
    if [ "$index" -eq "$target" ]; then
        echo "$line" >> "$file"
    fi

    index=$((index+1))

    if [ "$index" -eq "$count" ]; then
        index=0
    fi
done
