FROM centos:7
USER root

# Dependencies built from source
ARG B64_VERSION=1.2.1
ARG CARES_VERSION=1.13.0
ARG CMAKE_VERSION=3.5.1
ARG CURL_VERSION=7.61.1
ARG GOOGLETEST_REVISION=release-1.8.1
ARG GRPC_REVISION=v1.15.0
ARG JQ_VERSION=1.6
ARG JSONCPP_REVISION=0.10.7
ARG LUAJIT_VERSION=2.0.3
ARG NCURSES_VERSION=6_0_20150725
ARG PROMETHEUS_CPP_REVISION=v0.4.2
ARG PROTOBUF_VERSION=3.6.1
ARG TBB_VERSION=2018_U5

ARG NPROCS=6
ENV NPROCS=$NPROCS

## Install packaged dependencies
USER root
RUN yum -y install \
  autoconf automake binutils-devel bison ca-certificates \
  elfutils-libelf-devel file flex gettext git glibc-devel glibc-static \
  indent libtool make patchutils pkgconfig wget which \
  unzip libcap-ng-devel python libuuid-devel libz-devel \
  openssl-devel 
RUN yum -y install centos-release-scl
RUN yum -y install devtoolset-6-gcc devtoolset-6-gcc-c++

# We want to fail if the destination directory is there, hence mkdir (not -p).
RUN mkdir install-tmp

COPY install/*.sh install-tmp/

# Build dependencies from source
RUN ./install-tmp/install.sh

RUN ldconfig

# Copy files needed for generating proto code, building sysdig library and building collector
COPY build/protogen.mk /protogen.mk
COPY build/build-sysdig.sh /build-sysdig.sh
COPY build/build-collector.sh /build-collector.sh

RUN chmod 700 /build-collector.sh
RUN chmod 700 /build-sysdig.sh

