FROM centos:8

ARG NPROCS=6
ENV NPROCS=$NPROCS

## Install packaged dependencies
USER root
RUN yum -y install \
  autoconf automake binutils-devel bison ca-certificates \
  elfutils-libelf-devel file flex gettext git glibc-devel \
  libtool make patchutils pkgconfig wget which \
  unzip libcap-ng-devel python2 libuuid-devel libcurl-devel \
  openssl-devel 
RUN yum -y groupinstall "Development Tools"

# The following command would only install cmake 3.11; we need 3.13+ to build gRPC properly
# RUN yum -y install cmake
RUN curl -L https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2.tar.gz | tar -xzf - && \
    cd cmake-3.15.2 && ./bootstrap && make && make install && cd .. && rm -rf cmake-3.15.2

# We want to fail if the destination directory is there, hence mkdir (not -p).
RUN mkdir install-tmp

COPY install/*.sh install-tmp/

# Build dependencies from source
RUN ./install-tmp/install.sh

RUN ldconfig

# Copy files needed for generating proto code, building sysdig library and building collector
COPY build/protogen.mk /protogen.mk
COPY build/build-sysdig.sh /build-sysdig.sh
COPY build/build-collector.sh /build-collector.sh

RUN chmod 700 /build-collector.sh
RUN chmod 700 /build-sysdig.sh
