---
- name: Build and push collector image
  hosts: all

  environment:
    BUILD_BUILDER_IMAGE: "{{ ansible_env.BUILD_BUILDER_IMAGE | default(omit) }}"
    COLLECTOR_BUILDER_TAG: "{{ ansible_env.COLLECTOR_BUILDER_TAG }}"
    PLATFORM: "{{ ansible_env.PLATFORM }}"
    COLLECTOR_TAG: "{{ ansible_env.COLLECTOR_TAG | default(omit) }}"

  tasks:
    - name: Build the collector image
      community.general.make:
        chdir: "{{ lookup('env', 'GITHUB_WORKSPACE') }}"
        target: image

    - name: Login to quay.io
      community.docker.docker_login:
        registry_url: quay.io
        username: "{{ stackrox_io_username }}"
        password: "{{ stackrox_io_password }}"

    - name: Push slim to quay.io/stackrox-io
      community.docker.docker_image:
        name: "{{ collector_image }}"
        repository: "{{ collector_image }}-{{ arch }}-slim"
        push: true
        source: local

    - name: Push base to quay.io/stackrox-io
      community.docker.docker_image:
        name: "{{ collector_image }}"
        repository: "{{ collector_image }}-{{ arch }}-base"
        push: true
        source: local

    - name: Logout of quay.io
      community.docker.docker_login:
        registry_url: quay.io
        state: absent
      when: true
