---
- name: Build Collector Integration Test image
  hosts: all

  environment:

  tasks:
    - set_fact:
        platforms: "linux/amd64,linux/ppc64le,linux/s390x,linux/arm64"
      when: build_multi_arch

    - set_fact:
        platforms: "linux/amd64"
      when: not build_multi_arch

    - set_fact:
        collector_root: "{{ lookup('env', 'GITHUB_WORKSPACE') }}"

    - name: Login to quay.io
      community.docker.docker_login:
        registry_url: quay.io
        username: "{{ rhacs_eng_username }}"
        password: "{{ rhacs_eng_password }}"

    - name: Build the test image
      shell:
        # Reasons for not using community.docker.docker_image:
        #   - it does not support multiple platforms (we could parallelize
        #     via GHA, but the build is fast enough without, so this is simpler)
        # Reasons for not using the build-image make target
        #   - we can push the images and manifest in a single command. The make
        #     target can be used for local development and testing.
        docker buildx build --push \
          --platform "{{ platforms }}" \
          -t '{{ test_image }}' \
          {{ collector_root }}/integration-tests
      register: build_result

    - debug:
        msg: |
          Pushed {{ test_image }}

    - name: Logout of quay.io
      community.docker.docker_login:
        registry_url: quay.io
        state: absent
      when: true

