---
- name: Build Collector Integration Test image
  hosts: all

  environment:
    PLATFORMS: "linux/amd64,linux/ppc64le,linux/s390x"

  tasks:
    - set_fact:
        collector_root: "{{ lookup('env', 'GITHUB_WORKSPACE') }}"

    - name: Login to quay.io
      community.docker.docker_login:
        registry_url: quay.io
        username: "{{ rhacs_eng_username }}"
        password: "{{ rhacs_eng_password }}"

    - name: Build the test image
      shell:
        docker buildx build --push \
          --platform "${PLATFORMS}" \
          --build-arg QA_TAG="{{ lookup('file', collector_root + '/integration-tests/container/QA_TAG') }}" \
          -t '{{ test_image }}' \
          {{ collector_root }}/integration-tests
      register: build_result

    - debug:
        msg: |
          Pushed {{ test_image }}

    - name: Logout of quay.io
      community.docker.docker_login:
        registry_url: quay.io
        state: absent
      when: true

