---
- name: Create Build VMs
  hosts: localhost
  tags:
    - setup
  tasks:
    - name: Create VMs for each architecture
      include_role:
        name: create-all-vms
      vars:
        vm_list: "{{ virtual_machines }}"
  post_tasks:
    # We have all the VMs created now, so refresh the inventory - this allows
    # us to use the provisioning role on the VMs we just created
    - meta: refresh_inventory

- name: Provision Build VMs
  hosts: "job_id_{{ job_id }}"
  roles:
    - provision-vm
  gather_facts: no
  strategy: free
  become: yes
  tags:
    - setup
    - provision
