---
- name: Run integration tests
  vars_files:
    - vars/all.yml
  hosts: "platform_*:&job_id_{{ job_id }}"
  strategy: free
  gather_facts: false
  environment:
    REMOTE_HOST_TYPE: ssh
    SSH_ADDRESS: "{{ ansible_host }}"
    SSH_PORT: "{{ ansible_port }}"
    SSH_USER: "{{ ansible_user }}"
    SSH_KEY_PATH: "{{ ansible_ssh_private_key_file }}"
    COLLECTOR_IMAGE: "quay.io/rhacs-eng/collector:3.11.0"
    VM_CONFIG: "{{ vm_config }}"
  
  tasks:
    - set_fact:
        logs_root: "{{ collector_root }}/integration-tests/container-logs/{{ vm_config }}"

    - name: Log into quay.io
      shell:
        cmd: "docker login -u {{ quay_username }} --password-stdin quay.io"
        stdin: "{{ quay_password }}"

    - name: Cleanup old containers
      shell: "docker rm -f $(docker ps -aq) >/dev/null 2>&1 || true"

    - name: Run integration tests
      shell: "make -C {{ collector_root }} {{ collector_test | default('ci-integration-tests') }}"
      environment:
        COLLECTION_METHOD: "{{ item }}"
      with_items:
        - ebpf
      register: test_result
      delegate_to: localhost
        
    - name: Write integration test log
      copy:
        content: "{{ test_result.results[0].stdout }}"
        dest: "{{ logs_root }}/integration-test.log"
      delegate_to: localhost

    - name: Run benchmarks
      shell: "make -C {{ collector_root }} ci-benchmarks"
      environment:
        COLLECTION_METHOD: "{{ item }}"
      with_items:
        - ebpf
      register: benchmark_result
      when: run_benchmarks|bool == true
      delegate_to: localhost

    - name: Write benchmark log
      copy:
        content: "{{ benchmark_result.results[0].stdout }}"
        dest: "{{ logs_root }}/{{ vm_config }}/benchmark.log"
      delegate_to: localhost
      when: run_benchmarks|bool == true

    - name: Report
      shell: "make -C {{ collector_root }}/integration-tests report"
      environment:
        LOG_FILE: "{{ logs_root }}/integration-test.log"
      delegate_to: localhost

