---
- name: Run integration tests
  vars_files:
    - vars/all.yml
  # using platform_*:&job_id here ensures that ansible imports
  # group_vars/platform_*.yml for the relevant platform, e.g.
  # flatcar where we need to use a custom python interpreter.
  hosts: "platform_*:&job_id_{{ job_id }}"
  strategy: free
  gather_facts: false
  environment:
    REMOTE_HOST_TYPE: ssh
    SSH_ADDRESS: "{{ ansible_host }}"
    SSH_PORT: "{{ ansible_port }}"
    SSH_USER: "{{ ansible_user }}"
    SSH_KEY_PATH: "{{ ansible_ssh_private_key_file }}"
    COLLECTOR_IMAGE: "quay.io/rhacs-eng/collector:3.11.0"
    VM_CONFIG: "{{ vm_config }}"
  
  tasks:
    - set_fact:
        logs_root: "{{ collector_root }}/integration-tests/container-logs/{{ vm_config }}"

    - name: Log into quay.io
      shell:
        cmd: "docker login -u {{ quay_username }} --password-stdin quay.io"
        stdin: "{{ quay_password }}"

    - name: Run Integration Tests
      include_tasks: tasks/test-collection-method.yml
      vars:
        collection_method: "{{ item }}"
      with_items:
        - ebpf
        - kernel-module

