apiVersion: tekton.dev/v1
kind: PipelineRun

metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stackrox/collector?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "500"
    pipelinesascode.tekton.dev/on-cel-expression: |
      (event == "push" && target_branch.matches("^(master|release-.*)$")) || event == "pull_request"
  labels:
    appstudio.openshift.io/application: acs
    appstudio.openshift.io/component: collector
    pipelines.appstudio.openshift.io/type: build
  name: collector-build
  namespace: rh-acs-tenant

spec:
  params:
  - name: dockerfile
    value: collector/container/konflux.Dockerfile
  - name: git-url
    value: '{{repo_url}}'
  - name: image-expires-after
    # TODO(ROX-24530): return expiration for non-released images to 13w
    value: '52w'
  - name: output-image-repo
    value: quay.io/rhacs-eng/collector
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: rebuild
    value: 'true'
  # TODO(ROX-20234): Enable hermetic builds
  # - name: hermetic
  #   value: "true"
  # No language dependencies are required for collector image.
  - name: prefetch-input
    value: ''
  - name: clone-depth
    value: '0'
  - name: clone-fetch-tags
    value: 'true'
  - name: clone-submodules
    value: 'true'
  - name: build-source-image
    value: 'true'

  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'

  taskRunSpecs:
  - pipelineTaskName: clone-repository
    stepSpecs:
    - name: create-trusted-artifact
      computeResources:
        limits:
          memory: 3Gi
        requests:
          memory: 3Gi
  # Only adjusting computeResources for amd64 build because
  # multi-arch builds happen off cluster
  - pipelineTaskName: build-container-amd64
    stepSpecs:
    - name: build
      # CPU requests are increased to speed up builds compared to the defaults.
      # Defaults: https://github.com/redhat-appstudio/build-definitions/blob/main/task/buildah/0.1/buildah.yaml#L126
      computeResources:
        limits:
          cpu: 4
        requests:
          cpu: 4

  timeouts:
    # The pipeline regularly takes >1h to finish.
    # When changing the value here, make sure to adjust wait-for-images time limit in .github/workflows/konflux-tests.yml
    tasks: 2h
    finally: 10m
    pipeline: 2h10m

  pipelineRef:
    name: collector-component-pipeline
