apiVersion: tekton.dev/v1
kind: PipelineRun

metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stackrox/collector?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "500"
    # TODO(ROX-21073): re-enable for all PR branches
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && (source_branch.contains("rhtap") || source_branch.contains("konflux"))
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: acs
    appstudio.openshift.io/component: collector
    pipelines.appstudio.openshift.io/type: build
  name: collector-on-pull-request
  namespace: rh-acs-tenant

spec:
  params:
  - name: dockerfile
    value: collector/container/konflux.Dockerfile
  - name: git-url
    value: '{{repo_url}}'
  - name: image-expires-after
    value: '13w'
  - name: output-image-repo
    value: quay.io/rhacs-eng/collector
  - name: output-tag-suffix
    value: '-latest'
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: rebuild
    value: 'true'
  # TODO(ROX-20234): Enable hermetic builds
  # - name: hermetic
  #   value: "true"
  # No language dependencies are required for collector image.
  - name: prefetch-input
    value: ''
  - name: clone-depth
    value: '0'
  - name: clone-fetch-tags
    value: 'true'
  - name: clone-submodules
    value: 'true'
  - name: build-source-image
    value: 'true'
  - name: build-target-stage
    value: collector

  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
  - name: subscription-manager-activation-key
    secret:
      secretName: subscription-manager-activation-key

  # The pipeline regularly takes >1h to finish.
  timeouts:
    pipeline: 1h30m0s

  pipelineRef:
    name: collector-component-pipeline
