FROM ubuntu:14.04

# Install our dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        apt-transport-https \
        autoconf \
        automake \
        build-essential \
        ca-certificates \
        cmake \
        curl \
        git \
        g++-4.8 \
        google-mock \
        libboost-regex-dev \
        libjsoncpp-dev \
        libssl-dev \
        libtool \
        unzip \
        ;

# We want to fail if the destination directory is there, hence mkdir (not -p).
RUN mkdir build

# prometheus-cpp
COPY build/install_prometheus.sh build/install_prometheus.sh
RUN build/install_prometheus.sh

# GoogleMock (and GoogleTest) are opinionated about how to install the library
RUN cd /usr/src/gmock \
        && cmake CmakeLists.txt \
        && make \
        && cp -R /usr/src/gmock/gtest/include/gtest /usr/local/include/gtest \
        && cp libgmock*.a /usr/lib \
        && cp gtest/libgtest*.a /usr/lib \
        ;

# cURL 7.42 or higher is required for UNIX socket access
ARG CURL_REVISION=curl-7_49_1
COPY build/install_libcurl.sh build/install_libcurl.sh
RUN build/install_libcurl.sh

# librdkafka v0.9.0 introduced a consistent hash message partitioner.
ARG RDKAFKA_REVISION=v0.9.3
COPY build/install_rdkafka.sh build/install_rdkafka.sh
RUN build/install_rdkafka.sh

# Clean up the build directory we created.
RUN rm -rf tmp-build

# Prepare everything, build, and run tests
RUN mkdir -p /src/build
COPY container/libs/libsysdignative.so /usr/local/lib/libsysdignative.so
COPY . /src
WORKDIR /src/build
CMD rm -f CMakeCache.txt && cmake .. && make clean all && ./runUnitTests
