name: Check driver failures

on:
  workflow_call:
    inputs:
      logs-artifact:
        required: true
        type: string
        description: |
          Artifact name where driver build logs have been stored.

jobs:
  check-failures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore failure files
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ inputs.logs-artifact }}
          merge-multiple: true
          path: /tmp/FAILURES

      - name: Check build failures
        run: |
          FAILURES_DIR=/tmp/FAILURES/ ${{ github.workspace }}/kernel-modules/build/drivers-build-failures.sh

      - name: Slack notification
        if: failure() && github.event_name != 'pull_request'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_COLLECTOR_ONCALL_WEBHOOK }}
          SLACK_CHANNEL: team-acs-collector-oncall
          SLACK_COLOR: ${{ job.status }}
          SLACK_LINK_NAMES: true
          SLACK_TITLE: Driver build check failed
          MSG_MINIMAL: actions url,commit
          SLACK_MESSAGE: |
            @acs-collector-oncall
