name: Retag slim image as full for PRs

on:
  workflow_call:
    inputs:
      collector-tag:
        type: string
        required: true
        description: |
          The tag used to build the collector image, usually extracted from the
          collector-slim.yml workflow

jobs:
  retag-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Pull slim image
        run: |
          docker pull quay.io/stackrox-io/collector:${{ inputs.collector-tag }}-slim

      - name: Login to quay.io/stackrox-io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_STACKROX_IO_RW_USERNAME }}
          password: ${{ secrets.QUAY_STACKROX_IO_RW_PASSWORD }}

      - name: Retag and push collector to stackrox-io
        run: |
          docker tag \
            quay.io/stackrox-io/collector:${{ inputs.collector-tag }}-slim \
            quay.io/stackrox-io/collector:${{ inputs.collector-tag }}
          docker tag \
            quay.io/stackrox-io/collector:${{ inputs.collector-tag }}-slim \
            quay.io/stackrox-io/collector:${{ inputs.collector-tag }}-latest

          docker push quay.io/stackrox-io/collector:${{ inputs.collector-tag }}
          docker push quay.io/stackrox-io/collector:${{ inputs.collector-tag }}-latest

      - name: Login to quay.io/rhacs-eng
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_RHACS_ENG_RW_USERNAME }}
          password: ${{ secrets.QUAY_RHACS_ENG_RW_PASSWORD }}

      - name: Retag and push collector to rhacs-eng
        run: |
          docker tag \
            quay.io/stackrox-io/collector:${{ inputs.collector-tag }}-slim \
            quay.io/rhacs-eng/collector:${{ inputs.collector-tag }}

          docker push quay.io/rhacs-eng/collector:${{ inputs.collector-tag }}
