name: Setup Runner
on:
  workflow_call:
    secrets:
      GOOGLE_CREDENTIALS_COLLECTOR_SVC_ACCT:
        required: true

jobs:
  setup_runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install python dependencies
        run: python -m pip install -r ansible/requirements.txt

      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_COLLECTOR_SVC_ACCT }}'

      - name: Setup GCP
        uses: 'google-github-actions/setup-gcloud@v1'


