name: Update driver cache

on:
  workflow_call:

jobs:
  update-driver-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Update driver cache
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-cache') }}
        run: |
          for module_version_dir in /tmp/kobuild-tmp/versions-src/*; do
            module_version="$(basename "${module_version_dir}")"
            mkdir -p "/tmp/kernel-modules/$module_version/"

            gsutil -m rsync -r \
              "gs://collector-modules-osci/$module_version/" \
              "/tmp/kernel-modules/$module_version/" || true
          done

          BASE_DIR=/tmp \
            ${{ github.workspace }}/.openshift-ci/drivers/scripts/sanitize-drivers.py
